import { Inter } from "next/font/google";
import "../globals.css";
import { ThemeProvider } from "@/components/provider/theme-provider"
import Header from "@/components/Header";
import SideBar from "@/components/SideBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body className={`${inter.className} flex items-start justify-between`}>
                <ThemeProvider
                    attribute="class"
                    defaultTheme="system"
                    enableSystem
                    disableTransitionOnChange
                >
                    <SideBar />
                    <main className=" w-full h-full">
                        {children}
                    </main>
                </ThemeProvider>
            </body>
        </html>
    );
}
